### ISSUE TITLE
Сrash when try to open settings on linux

### ISSUE THREAD

**Issue by farwayer** [ntadej/tano#48]
archlinux
xorg: 1.14.4
qt: 4.8.5
tano: master
wm: i3, tryed openbox and cinnamon also
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5e46a7a in strlen () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff5e46a7a in strlen () from /usr/lib/libc.so.6
#1  0x00007ffff3054425 in XSetCommand () from /usr/lib/libX11.so.6
#2  0x00007ffff3058831 in XSetWMProperties () from /usr/lib/libX11.so.6
#3  0x00007ffff6dc2a57 in QWidgetPrivate::create_sys(unsigned long, bool, bool) () from /usr/lib/libQtGui.so.4
#4  0x00007ffff6d7a47d in QWidget::create(unsigned long, bool, bool) () from /usr/lib/libQtGui.so.4
#5  0x00007ffff6d829ca in QWidget::setVisible(bool) () from /usr/lib/libQtGui.so.4
#6  0x00007ffff71d6ebe in QDialog::setVisible(bool) () from /usr/lib/libQtGui.so.4
#7  0x00007ffff71d6966 in QDialog::exec() () from /usr/lib/libQtGui.so.4
#8  0x00007ffff787782f in MainWindow::showSettings (this=this@entry=0x7fffffffe5f0) at /tmp/yaourt-tmp-farwayer/aur-tano-git/src/tano-build/src/widgets/MainWindow.cpp:775
#9  0x00007ffff78eb068 in MainWindow::qt_static_metacall (_o=0x7fffffffe5f0, _c=<optimized out>, _id=10, _a=0x7fffffffd680) at /tmp/yaourt-tmp-farwayer/aur-tano-git/src/tano-build/src/widgets/moc_MainWindow.cpp:112
#10 0x00007ffff6818b48 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/libQtCore.so.4
#11 0x00007ffff6d2dfd2 in QAction::triggered(bool) () from /usr/lib/libQtGui.so.4
#12 0x00007ffff6d2f9a3 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQtGui.so.4
#13 0x00007ffff6d2fafc in QAction::event(QEvent*) () from /usr/lib/libQtGui.so.4
#14 0x00007ffff6d3412c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#15 0x00007ffff6d3a6f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#16 0x00007ffff6804ebd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
#17 0x00007ffff6d65406 in ?? () from /usr/lib/libQtGui.so.4
#18 0x00007ffff6d65534 in ?? () from /usr/lib/libQtGui.so.4
#19 0x00007ffff6d3b9c3 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#20 0x00007ffff6804ebd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
#21 0x00007ffff6dce6a9 in ?? () from /usr/lib/libQtGui.so.4
#22 0x00007ffff6dcea49 in ?? () from /usr/lib/libQtGui.so.4
#23 0x00007ffff6daa9bf in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/libQtGui.so.4
#24 0x00007ffff6dd11b2 in ?? () from /usr/lib/libQtGui.so.4
#25 0x00007ffff4757296 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#26 0x00007ffff47575e8 in ?? () from /usr/lib/libglib-2.0.so.0
#27 0x00007ffff475768c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#28 0x00007ffff6831b25 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#29 0x00007ffff6dd1266 in ?? () from /usr/lib/libQtGui.so.4
#30 0x00007ffff6803b1f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#31 0x00007ffff6803e15 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#32 0x00007ffff6808f4b in QCoreApplication::exec() () from /usr/lib/libQtCore.so.4
#33 0x000000000040276d in main (argc=<optimized out>, argv=0x7fffffffe828) at /tmp/yaourt-tmp-farwayer/aur-tano-git/src/tano-build/src/player/main.cpp:45
```

**Comment by ntadej** [comment]
As Tano is now Qt 5 only, I'm closing this. Feel free to reopen if this will still be reproducible with Qt5.
